package edu.utn.gestion.ui;

import edu.utn.gestion.ui.dialog.book.BooksManagementDialog;
import edu.utn.gestion.ui.dialog.customer.CustomersManagementDialog;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.WindowConstants;

import org.apache.log4j.Logger;

/**
 *
 * @author gerardo
 */
public class MainFrame extends JFrame {
    private static final Logger LOGGER = Logger.getLogger(MainFrame.class);
    private static final String LOOK_AND_FEEL_DEFAULT_VALUE = "Nimbus";
    private static final MainFrame INSTANCE = new MainFrame();

    private JMenu menuFile;
    private JMenu menuEdit;
    private JMenu menuHelp;
    private JMenuBar menuBarGestionApp;
    private JMenuItem menuItemAbout;
    private JMenuItem menuItemBooks;
    private JMenuItem menuItemCustomers;
    private JMenuItem menuItemEmployee;
    private JMenuItem menuItemExit;

    /**
    * Creates new form MainFrame
    */
    private MainFrame() {
        this.initLookAndFeel();
        this.initComponents();        
    }
    
    public static MainFrame getInstance() {
        return INSTANCE;
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.menuBarGestionApp = new JMenuBar();
        this.menuFile = new JMenu("File");
        this.menuItemExit = new JMenuItem("Exit");
        this.menuEdit = new JMenu("Edit");
        this.menuItemBooks = new JMenuItem("Books");
        this.menuItemCustomers = new JMenuItem("Customers");
        this.menuHelp = new JMenu("Help");
        this.menuItemAbout = new JMenuItem("About");

        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setTitle("GestionApp");

        this.menuFile.add(this.menuItemExit);
        this.menuEdit.add(this.menuItemBooks);
        this.menuEdit.add(this.menuItemCustomers);
        this.menuHelp.add(this.menuItemAbout);

        this.menuBarGestionApp.add(this.menuFile);
        this.menuBarGestionApp.add(this.menuEdit);
        this.menuBarGestionApp.add(this.menuHelp);

        this.setJMenuBar(this.menuBarGestionApp);


        this.menuItemBooks.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
                menuItemBooksActionPerformed(event);
            }
        });

        this.menuItemCustomers.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent event) {
                menuItemCustomersActionPerformed(event);
            }
        });


        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        this.setSize(new Dimension(717, 532));
        this.setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemBooksActionPerformed(ActionEvent event) {
        new BooksManagementDialog(this, true).setVisible(true);
    }

    private void menuItemCustomersActionPerformed(ActionEvent event) {
        new CustomersManagementDialog(this, true).setVisible(true);
    }

    /**
    *  Executes the UI.
    *
    * @param args
    */
    public void execute(String args[]) {
        this.main(args);
    }

    /**
    * @param args the command line arguments
    */
    private void main(String args[]) {
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                INSTANCE.setVisible(true);
            }
        });
    }

    /**
    *  Sets the default look and feel for the application.
    */
    private void initLookAndFeel() {
        try {
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if (LOOK_AND_FEEL_DEFAULT_VALUE.equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            LOGGER.error(ex);
        }
    }
}
